language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: uGldZ6Dlhrt8z+65dKx8W6rkmPaR5WXtwalbM2qVZBr1RZ96rgRLvqyYgRx28CLJbmPPOIiFyTcWK7K+Ke9J9DRhrqYzKY2SxR6fbIW3uQNwfTtx5/khHxrbSHmur7J22fNIAclCwwUrVHCKrBRR8G/Bw3vdREBym/cD9GKvBApLH3rPWlCqlcZAwMmf3UgSGC+55Cc4dYxmNr+JvK/IsBW1ijxf37I1D+g8OhTDd/AReQLbWElHoAJwtC32UdwLOfYbvmLuUCef3R3xm035dXHZCCV0iD2ZMvgoUJH1f1wfeJXOYBTrB1YWAHHtf2WFFfd6hHn3S7+iiGB2OmTrad6wx6R7j6PoT68ndppLnccyCRLMACkKGsQTt5z211vxfhlgeQnGxwU+iVa6Uv7Xylczoau6E51ZSrGZdz1R3GzqMmbN3v4vEbJBTTDA7hfYsazYApZ9en7rBj+AH2JmQ9RwtsWQnmNtbeTmW0mwXbuGahzupz1C7zzj+jhzUwmBGDI35eqFByXqIRI/lgB5BqmX/JDiVugTdwQhNfXtUmk0IeTibuMl713rM3rCgGtsJDxEpk48MaIF0SqbhzVfjvEf3qZUYC8s7G0XLM7hv7wOuzsnviSfzOIH/d+i9SiX1fdQFDsOuygmV1YbJ7xQBckacmYfLa62EQH6B/61/Qw=
  app: project-103-sharks
  on:
    repo: uva-cs3240-f19/project-103-sharks
